### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by jspeed-meyers** [IQTLabs/AuraBorealisApp#1]
@kdobolyi, can you please add a thorough README? Sections should include:

- Brief description of project
- Explanation of how to use it
- Feature roadmap
- Contact information for our group (use jmeyers@iqt.org)
- Links to relevant work, including past IQT Labs blog posts
- Anything else you think would be useful

**Comment by kdobolyi** [comment]
I added a start here, but feel free to elaborate
